services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    env_file:
      - .env
    volumes:
      - mongodb_data_container:/data/db

  hotel-netology:
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - mongodb
    env_file:
      - .env
volumes:
  mongodb_data_container: